apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: deepseek-r1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - name: openweb-http
          containerPort: 8080
          protocol: TCP
        env:
        - name: OLLAMA_BASE_URL
          value: "http://deepseek-r1-svc.deepseek-r1.svc.cluster.local"
        - name: WEBUI_SECRET_KEY
          value: "Secretkey"            
        volumeMounts:
        - name: webui-data
          mountPath: /app/backend/data
      volumes:
      - name: webui-data
        persistentVolumeClaim:
          claimName: openwebui-data
      restartPolicy: Always
