kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deepseek-70b
  namespace: deepseek-r1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: freenas-nfs-csi
  volumeMode: Filesystem