kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deepseek-r1-pvc
  namespace: deepseek-r1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: freenas-nfs-csi
  volumeMode: Filesystem
