kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: deepseek-r1-70b
  namespace: deepseek-r1
spec:
  to:
    kind: Service
    name: deepseek-r1-70b
  tls: null
  port:
    targetPort: http